apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardware-cloud-console
  labels:
    app: boardware-cloud-console
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boardware-cloud-console
  template:
    metadata:
      labels:
        app: boardware-cloud-console
    spec:
      containers:
        - name: boardware-cloud-console
          image: registry.boardware.com/bwc/core@sha256:e132b3aa02cdd2691e283989a060de894d3f35f7cfd8a77625240eecf96c9581
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/live
              port: 80
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/ready
              port: 80
              scheme: HTTP
      imagePullSecrets:
        - name: harbor